### ISSUE TITLE
Convert Chef recipe to leverage runit instead of systemd to make it more Docker friendly

### ISSUE THREAD

**Issue by rrxtns** [rrxtns/hangops-jobbot#32]
[Swipe all or parts from here](https://github.com/chef-cookbooks/hubot/tree/master/recipes)

get this using runit vs. systemd

**Comment by gabinante** [comment]
This cookbook configures runit for hubot, we can probably steal their code:

https://github.com/chef-cookbooks/hubot/tree/master/recipes

**Comment by rowleyaj** [comment]
Could the hubot cookbook be used to install jobbot?

**Comment by rrxtns** [comment]
Got this mostly working - leaving this open for now.

**Comment by rrxtns** [comment]
Aside from a bug in docker, this is working out well, closing
